[tasks.schemas]
script = [
  "cargo run -- schema cv > data/cv.schema.json",
  "cargo run -- schema assets > data/assets.schema.json",
  "cargo run -- schema technos > data/technos.schema.json", 
]

[tasks.index]
# TODO check how to use proper git CI job to build index.html
script = [
  'cargo run -- build data/cv.yml | npx prettier@latest --parser html > index.html'
]

[tasks.dev]
script = [
  'xdg-open cv.html',
  'cargo watch -w src -w data -s "cargo make index"'
]